package com.example.mod_data_products.models

data class Product(
    val id: Long,
    val sku: String,
    val inStock: Boolean,
    val sizeInStock: List<Size>,
    val availableSizes: List<AvailableSize>,
    val handle: String,
    val title: String,
    val description: String,
    val type: String,
    val gender: List<Gender>,
    val fit: String?,
    val labels: List<ProductLabel>?,
    val colour: String,
    val price: Int,
    val compareAtPrice: Int?,
    val discountPercentage: Int?,
    val featuredMedia: ProductMedia,
    val media: List<ProductMedia> = emptyList(),
    val objectID: String,
)

object SampleProducts {
   val values = sequenceOf(
        Product(
            id = 1L,
            sku = "SKU-1",
            inStock = true,
            sizeInStock = emptyList(),
            availableSizes = emptyList(),
            handle = "",
            title = "Product 1",
            description = "",
            type = "",
            gender = listOf(Gender.FEMALE),
            fit = "",
            labels = listOf(ProductLabel.NEW),
            colour = "Black",
            price = 1000,
            compareAtPrice = null,
            discountPercentage = null,
            featuredMedia = SampleProductMedia.values.first(),
            media = emptyList(),
            objectID = "1",
        ),
        Product(
            id = 2L,
            sku = "SKU-2",
            inStock = false,
            sizeInStock = emptyList(),
            availableSizes = emptyList(),
            handle = "",
            title = "Product 2",
            description = "",
            type = "",
            gender = listOf(Gender.MALE),
            fit = "",
            labels = null,
            colour = "Blue",
            price = 1000,
            compareAtPrice = null,
            discountPercentage = null,
            featuredMedia = SampleProductMedia.values.first(),
            media = emptyList(),
            objectID = "1",
        ),
    )
}